project_id = "cfovatohfdfryweosyux"

[functions.send-order-email]
verify_jwt = false

[functions.send-booking-email]
verify_jwt = false

[functions.get-paypal-client-id]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
